name: security

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  test:
    name: Test security pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Pipeline ready
        run: echo "Security pipeline is ready"
